require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - bin/**/*
    - examples/**/*
    - .bundle/**/*
    - .yardoc**/*
    - _yardoc/**/*
    - coverage/**/*
    - doc/**/*
    - pkg/**/*
    - spec/reports/**/*
    - spec/mocks/**/*
    - tmp/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Naming/FileName:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

Metrics/MethodLength:
  Max: 15
