version: '3.8'
services:
  config:
    build: .
    stdin_open: true
    tty: true
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    volumes:
      - .:/cloud-config
      - ~/.gitconfig:/root/.gitconfig
      - /run/host-services/ssh-auth.sock:/ssh-agent
    networks:
      - cloud-config

  yardoc:
    build: .
    command: yard server -r
    volumes:
      - .:/cloud-config
    ports:
      - 8808:8808
    networks:
      - cloud-config

networks:
  cloud-config:
    name: cloud_config
